version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: insomniatso/foodgarm-backend:latest
    restart: always
    command: >
      bash -c "python manage.py makemigrations users &&
      python manage.py migrate users &&
      python manage.py makemigrations recipes &&
      python manage.py migrate recipes &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      python manage.py loaddata data_dump.json &&
      gunicorn --bind 0:8000 foodgram.wsgi"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: insomniatso/foodgarm-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
       - backend

volumes:
  static_value:
  media_value:
  postgres_data:
